### ISSUE TITLE
BOM Alternatives and Notes

### ISSUE THREAD

**Issue by Chase-san** [LordxOsmosisx86/DMG-KGDU-10-Plus-FRAM-Upgraded-PCB#1]
In case some of the rarer parts are out of stock, I have made up a list of otherwise similar parts for reference purposes. Every part links directly to the relevant datasheet. I hve also included parts that are not recommended despite appearing compatible.

There are so many 0603 resistors and capacitors in existence I don't feel that those require a listing here.

| Ref | Manufacturer | Part | Notes |
| --- | ------------ | ---- | ------ |
| U3 | infineon | [FM28V020](https://www.mouser.com/datasheet/2/196/CYPR_S_A0011167037_1-3004858.pdf) | Not recommended. This chip has an absolute maximum voltage of 4.5v. A gameboy cart operates at a nominal voltage of 5v. It will likely work but its life will be drastically reduced. |
| U3 | infineon | [FM1808B](https://www.mouser.com/datasheet/2/196/CYPR_S_A0011134546_1-3004721.pdf) | Inferior. Has a lower memory endurance but is otherwise compatible. |
| X1 | ESC | [ECS-.327-12.5-13X-C](https://www.mouser.com/datasheet/2/122/ECS_3x8X_2x6X_1X5X-5572.pdf) | Nearly identical. |
| X1 | ABRACON | [AB26TRB-32.768KHZ-T](https://www.mouser.com/datasheet/2/3/AB26TRB-2089610.pdf) | Somewhat smaller, and has legs that will need to be straightened before install. Has bulge at base of crystal. |
| X1 | PERICOM | [G13270009](https://www.mouser.com/datasheet/2/115/Diodes_08122021_G13270009-2509648.pdf) | Slightly wider at base rather than a perfect cylinder. |
| Batt 2025 | Linx | [BAT-HLD-001 ](https://www.mouser.com/datasheet/2/238/LNNC_S_A0002913840_1-2550745.pdf) | Not recommended despite nearly identical footprint. At 4.2mm in height this exceeds the maximum case clearance. |
| Batt 2025 | Linx | [BAT-HLD-002](https://www.mouser.com/datasheet/2/238/bat_hld_002_smt-1659519.pdf) | Nearly identical footprint, but shorter. Designed for CR2016 batteries. Technically tall enough to fit a CR2025. |

These are the Ram Protection ICs. Any of these will (probably) work. There are many revisions of games so the same game may have come with more than one of these. Chip Label is what is printed physically on the chip, a # can be any character. I included where I found this chip just to help relieve any stress from using an odd chip.

| Ref | Manufacturer | Part | Chip Label | Found In | Notes | 
| --- | ------------ | ---- | ---------- | ------- | ------ | 
| U4 | MITSUMI | [MM1143A](https://www.digchip.com/datasheets/parts/datasheet/304/MM1134-pdf.php) | M&nbsp;### 134A | Pokemon Gold (Europe, USA), Pokemon Crystal (Aus, USA&nbsp;Rev&nbsp;1) | Recommended. Common. Used by almost everything. Probably the reference IC since it's printed on the PCB. | 
| U4 | MITSUMI | [MM1026A](http://www.datasheetq.com/datasheet-download/894569/1/Mitsumi/MM1026) | M&nbsp;### 26A | Pocket Monsters Green (Jap), Pocket Monsters Pikachu (Jap), Pokemon Blue (USA) | Compatible. Less common. Never used on GSC as far as I can find. | 
| U4 | ROHM | [BA6129AF](https://www.mouser.com/datasheet/2/348/Rohm-BA6129AF_BA6162_BA6162F-1201632.pdf) | 6129A #### | Pokemon Red (USA), Pokemon Silver (USA) | Compatible. Less common. | 
| U4 | ROHM | BA6735 | 6735 #### | Pokemon Silver (USA), Pokemon Crystal (USA) | Compatible. Less common. |

**Comment by Chase-san** [comment]
[Osh Park](https://oshpark.com/shared_projects/EM2j1Td4) doesn't have the volume of chinese manufacturers and so will take long to be produced and shipped.

**Comment by MelonGx** [comment]
I have one question:

Japanese FRAM modders said only FM1808-70-SG (the former model of FM1808B) was compatible with Nintendo 64 Transfer Pak (for Stadium series).

Does anyone test this for FM18W08 / FM1808B?
